export enum ActionType {
  GENERATE_NEW_BATCH = 'GENERATE_NEW_BATCH',
  EXTINGUISH_ITEM = 'EXTINGUISH_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
  RECYCLE_BULK_ITEMS = 'RECYCLE_BULK_ITEMS',
  ADD_TO_SHIPMENT = 'ADD_TO_SHIPMENT',
  REMOVE_FROM_SHIPMENT = 'REMOVE_FROM_SHIPMENT',
  SEND_SHIPMENT = 'SEND_SHIPMENT',
  FETCH_SHIPMENTS = 'FETCH_SHIPMENTS',
}
